#cloud-config
package_update: true
package_upgrade: true

packages:
  - wget
  - net-tools

runcmd:
  - wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - rm packages-microsoft-prod.deb
  - sudo apt-get update -y
  - sudo apt-get install -y aspnetcore-runtime-9.0
  - sudo apt update -y && sudo apt upgrade -y && sudo apt dist-upgrade -y && sudo apt autoremove -y && sudo apt auto-clean -y
  #- curl -sfL https://get.k3s.io | K3S_TOKEN=token sh - 
